apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: detect
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: detect 
  name: detect
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: detect 
    weight: 100 
  wildcardPolicy: None
