apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: detect
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: detect 
  name: detect
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: detect 
